language: ruby

rvm:
  - "1.9.3"

branches:
  only:
    - master

before_script:
  # setup config
  - "cp config/config.yml.template config/config.yml"

  # setup database
  - "cp config/database.yml.travis config/database.yml"
  - "rake db:create"
  - "rake db:migrate"

script: bundle exec rspec spec
